### PR TITLE
Hotfix/add matariki nz ph

### PR DESCRIPTION
**Pull request by benaitcheson**
!no-server

## Description of changes

Added Matariki Public Holiday. Link to government website [here](https://www.mbie.govt.nz/assets/matariki-dates-2022-to-2052-matariki-advisory-group.pdf).

## Notes for code reviewers

- There was no way of writing a method for these days so they were hard coded into the file.

### CODE REVIEW

**Comment by bagp1** [comment]
@benaitcheson Why was this closed?

**Comment by benaitcheson** [comment]
Accidentally tried merged into this repo instead of our forked repo. @bagp1

**Comment by bagp1** [comment]
Oh that explains the diff haha.

If your repo is similar to this one, I don't think your change is going to return you any Holidays for July. You're meant to use month 0 for things like Easter and Matariki which can potentially land on more than one month. 

Here's what I came up with 
https://github.com/holidays/definitions/pull/224/files

**Comment by benaitcheson** [comment]
That's amazing. Thank you so much!

**Pull request closed without merging**
