### PR TITLE
Correct colombia holiday.

### PR DESCRIPTION
**Pull request by ttwo32**
Correct colombia holiday.
See detail [this](https://github.com/holidays/definitions/commit/beba524a3331191a68af7d8c7a6f0a9c71ea46bf#diff-0d957262574f314a6d4f09cc55c48ee8)

### CODE REVIEW

**Comment by ttwo32** [comment]
Wooo.
When holidays name is duplicated other defition, test is failed.
'Corpus Christi' is duplicated  br.yaml and co.yaml.

At above this situation, 'make test' is failed, but 'make test-region REGION=co' is passed.
Why??

**Comment by ppeble** [comment]
@ttwo32 I am also seeing what you are describing. I see two problems while testing this PR that I will list below.

#### 1) Both 'San Pedro y San Pablo' and 'Sagrado Corazón' take place on the same day in 2014

This is a scenario I have seen before:

```ruby
~/Code/ppeble/holidays(master ✗) make console
bundle exec rake console
irb -r rubygems -I lib -r holidays.rb
irb(main):001:0> Holidays.on(Date.civil(2014, 6, 30), :co)
=> [{:date=>#<Date: 2014-06-30 ((2456839j,0s,0n),+0s,2299161j)>, :name=>"Sagrado Corazón", :regions=>[:co]}, {:date=>#<Date: 2014-06-30 ((2456839j,0s,0n),+0s,2299161j)>, :name=>"San Pedro y San Pablo", :regions=>[:co]}
```

The tests that are generated look like this:

```ruby
# Passes
assert_equal "Sagrado Corazón", (Holidays.on(Date.civil(2014, 6, 30), [:co])[0] || {})[:name]

...(other tests)...

# Fails because it is returned at position [1] in the array, not [0]
assert_equal "San Pedro y San Pablo", (Holidays.on(Date.civil(2014, 6, 30), [:co])[0] || {})[:name]
```

We probably should update the ruby test generator so that tests do not assume position `0` and instead iterate over each returned array to see if the desired holiday is present. For example, we could instead generate this in the test:

```ruby
Holidays.on(Date.civil(2014, 6, 30), :co).any? { |h| h[:name] == "San Pedro y San Pablo" }
```

This would return 'true' even if 'Sagrado Corazón' comes first.

However, at this time I don't have the bandwidth to do this and I can't guarantee that doing this would not break other tests. 

We are already testing 'San Pedro y San Pablo' is correctly returned in other years. My recommendation is to remove [this test](https://github.com/holidays/definitions/pull/132/files#diff-0d957262574f314a6d4f09cc55c48ee8R300) from your PR. While not ideal it is still safe and doesn't require any additional development work.

#### 2) 'Corpus Christi' tests pass when testing only ':co' region but fail when running entire suite

This is more serious to me and I don't have an explanation. I am going to dig into it this week and report back.

#### Additional note

Based on your original description I thought that you were seeing 'known' behavior. After researching further I realized that I was wrong and that we are seeing a legitimate problem.

During that initial period [I wrote a gist](https://gist.github.com/ppeble/fd26030d91df48e478fd3ba11066ba82) that described a scenario in which the loading of different regions could result in slightly different results. Even though I don't think it answers the problem you are reporting I thought I would link it rather than just delete it. Feel free to ignore if you aren't interested! 😄

**Comment by ppeble** [comment]
@ttwo32 At least two of the errors we are seeing in the ruby project are unrelated to your PR. I missed some `:ca` tests in https://github.com/holidays/definitions/pull/128 and it is causing some incorrect `Christmas Day` failures.

I fixed the issue in [this other PR](https://github.com/holidays/definitions/pull/133). Could you please give it a look? It is small. Once we merge it you can then rebase and it will cut down on noise while we investigate the `co` issues.

**Comment by ppeble** [comment]
@ttwo32 I believe I understand what is happening and I think we have a bug in the ruby code. If we have two holidays named the same thing but with different definitions then we receive different results depending on which region is loaded first. This would explain why running `REGION=co make test-region` passes but running `make test` fails. The `br` region must be loaded before the `co` region when running `make test`.

Take our example of `Corpus Christi`. In the [colombia definition](https://github.com/holidays/definitions/blob/master/co.yaml) it would fall on 2014-06-23 but in the [brazil definition](https://github.com/holidays/definitions/blob/master/br.yaml) it would fall on 2014-06-19.

Here is concrete output to show what I mean. First snippet is loading `co` first and it returns the right result:

```ruby
~/Code/ppeble/holidays(master ✗) make console
bundle exec rake console
irb -r rubygems -I lib -r holidays.rb
irb(main):001:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> []
irb(main):002:0> Holidays.on(Date.civil(2014, 6, 23), :co)
=> [{:date=>#<Date: 2014-06-23 ((2456832j,0s,0n),+0s,2299161j)>, :name=>"Corpus Christi", :regions=>[:co]}]
irb(main):003:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:co]
```

Second snippet is loading `br` first and it does _not_ return the right result:

```ruby
~/Code/ppeble/holidays(master ✗) make console
bundle exec rake console
irb -r rubygems -I lib -r holidays.rb
irb(main):001:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> []
irb(main):002:0> Holidays.on(Date.civil(2014, 6, 19), :br)
=> [{:date=>#<Date: 2014-06-19 ((2456828j,0s,0n),+0s,2299161j)>, :name=>"Corpus Christi", :regions=>[:br]}]
irb(main):003:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:br]
irb(main):004:0> Holidays.on(Date.civil(2014, 6, 23), :co)
=> []
irb(main):005:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:br, :co]
```

I will look into how we could address this on the ruby side. I will open an issue in the ruby repository to track the problem. Let's hold off on merging this PR until we have a resolution in the other repository.

**Comment by ppeble** [comment]
I have created the issue in the ruby repo: https://github.com/holidays/holidays/issues/344

**Comment by ttwo32** [comment]
@ppeble Thank you for reviewing this PR.
Yes,　that's right. I have two errors .
And second problem is serious to me, too.

**Comment by ttwo32** [comment]
>> My recommendation is to remove this test from your PR. While not ideal it is still safe and doesn't >> require any additional development work.
I agree.Wait a second.
I will do from now.:)

**Comment by ppeble** [comment]
@ttwo32 I have opened https://github.com/holidays/holidays/pull/346 to address the specific issue that was raised by this PR. When I test locally with my changes I receive the correct results:

```ruby
~/Code/ppeble/holidays(issue-344 ✗) make console
bundle exec rake console
irb -r rubygems -I lib -r holidays.rb
irb(main):001:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> []
irb(main):002:0> Holidays.on(Date.civil(2014, 6, 19), :br)
=> [{:date=>#<Date: 2014-06-19 ((2456828j,0s,0n),+0s,2299161j)>, :name=>"Corpus Christi", :regions=>[:br]}]
irb(main):003:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:br]
irb(main):004:0> Holidays.on(Date.civil(2014, 6, 23), :co)
=> [{:date=>#<Date: 2014-06-23 ((2456832j,0s,0n),+0s,2299161j)>, :name=>"Corpus Christi", :regions=>[:co]}]
irb(main):005:0> Holidays::Factory::Definition.regions_repository.all_loaded
=> [:br, :co]
irb(main):006:0>
```

I believe that after merging my ruby PR we should test and merge this PR.

**Comment by ttwo32** [comment]
@ppeble I am really thankful to you.

**Pull request merged**
