### PR TITLE
Add Serbian holiday definitions

### PR DESCRIPTION
**Pull request by spaceneedle2019**
Serbia is using the Cyrillic and Latin alphabeth

- rs_cyrl.yaml offers holiday definitions in Cyrillic
- rs_la.yaml offers holiday definitions in Latin
- Tests are included

### CODE REVIEW

**Comment by spaceneedle2019** [comment]
Seems to be that the Job was cancelled. Tests are okay, aren't it?

**Comment by ppeble** [comment]
Yes, not sure what is going on with the jruby build. Don't worry about it, things look good to me. 😄 

Sorry for the lack of response and thank you for your patience! I've had a very busy week. I will make sure to set aside some time to get through all of your PRs and get a release out during the week. Thanks!

**Comment by spaceneedle2019** [comment]
@ppeble Ahkay. Good to know. :)

No problem. This week I'm going to push some holiday templates for Georgia, Russia, Turkey and maybe some states of the USA, too. The reason is, we are using your cool Holidays gem for generating CSV data for our holiday planning tool. :)

**Comment by ttwo32** [comment]
@spaceneedle2019 
Sorry for slow response too.I'm very busy at this week...
I will check your PR too.
I appreciate your work.
Thanks.

**Comment by spaceneedle2019** [comment]
@ttwo32 No problem at all. Thank you for your response. :)

**Comment by spaceneedle2019** [comment]
Still needs a correction. Serbia is celebrating Easter in the Orthodox way.

**Pull request merged**
