### PR TITLE
Fix National Foundation Day name of japanese

### PR DESCRIPTION
**Pull request by kunitoo**
The exact name will contain the word "の".

see:
- [Wikipedia](https://en.wikipedia.org/wiki/National_Foundation_Day)
- [government link](http://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html#hourutsu)

### CODE REVIEW

**Comment by kunitoo** [comment]
Thank you for reviews. (レビューありがとうございます。 :jp: )
I have a question.
How can I run the test code of [under L255](https://github.com/holidays/definitions/pull/9/files#diff-819156192e9a91a3ac017a318cc4a724L255)? I did not understand how to do it :sweat_drops: 
(L255以下のテストコードはどのように実行すればよいでしょうか?実行方法が分かりませんでした :sweat_drops: :jp: )

**Comment by ttwo32** [comment]
@kunitoo おおっとすいません。
Woops. .
テスト自体は親のholidaysから実行します。
We can execute local definition's test on parent repository that is [holidays](https://github.com/holidays/holidays).

以下のステップを試していただけますか？
Could you read and do bellow steps ?

1. checkout [holidays](https://github.com/holidays/holidays)

2. execute `make update_defs` to checkout submodule.(sorry checkout submodule is master repo only)

3. modify your definition.

4. execute 'make generate'  to generate definition ruby file from YAML.

5. execute 'make test' (Please see [this guide](https://github.com/holidays/holidays/blob/master/CONTRIBUTING.md#local-development-helpers))

わからないことがあったら聞いてください。(^^)
If you have other question about holidays , please comment.:)

**Comment by ptrimble** [comment]
Sorry @ttwo32! I could have sworn that I set you up as a contributor on this new repo but I definitely did not. You are added now, feel free to merge. 👍

**Comment by ptrimble** [comment]
@kunitoo Also, this new 'separate' definitions repo is a new thing that I did. I would like to use these definitions in non-ruby projects. But...I don't know if this setup is 'good' or if it makes sense. If it is confusing to you please offer feedback, we can definitely make changes to make it easier for contributors.

Thank you so much for contributing!

**Comment by kunitoo** [comment]
@ttwo32 Thank you for answer to my question. I will try that.

**Comment by kunitoo** [comment]
@ptrimble Thank you for response and telling me why you are separate the repository.

**Pull request merged**
