### PR TITLE
Fix jruby on Travis CI

### PR DESCRIPTION
**Pull request by ppeble**

### CODE REVIEW

**Comment by ppeble** [comment]
This is a work in progress. I'm not entirely sure why jruby is failing but I'm pretty sure it's just a config issue.

**Comment by ttwo32** [comment]
'bundle' command not found when using jruby-head.
https://github.com/travis-ci/travis-ci/issues/5861

**Comment by ttwo32** [comment]
Bundler can use block at 'source' greater than ver 1.7.
So i fixed Gemfile .

**Comment by ppeble** [comment]
Closing in favor of https://github.com/holidays/definitions/pull/40

**Pull request closed without merging**
