### PR TITLE
FIX: tasmania / nsw / vic do not observe on Monday

### PR DESCRIPTION
**Pull request by SamSaffron**
https://worksafe.tas.gov.au/topics/laws-and-compliance/public-holidays
https://www.nsw.gov.au/living-nsw/school-and-public-holidays
https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2021

### CODE REVIEW

**Comment by SamSaffron** [comment]
Improves #189 which is missing fixes for Tasmania and NSW.

**Comment by evjan** [comment]
LGTM!

**Comment by ppeble** [comment]
I am terribly sorry for the delay. Could you rebase from the latest main branch to resolve the conflicts? I will then merge and include this in the latest release.

**Comment by ppeble** [comment]
Closing in favor of https://github.com/holidays/definitions/pull/285

**Pull request closed without merging**
