### PR TITLE
Correct and enhance German holiday definitions

### PR DESCRIPTION
**Pull request by spaceneedle2019**
- Add Berlin, Bremen, Hamburg, Niedersachsen, Schleswig-Holstein
- Change de_th_eichsfeld to de_th_cath because it affects the catholic communities Eichsfeld, Unstrut-Hainich-Kreis and Wartburgkreis
- Merge Fronleichnam entry
- Add de_by_cath for catholic communities in Bavaria; Maria Himmelfahrt is not a Bavaria-wide holiday
- Mariä Himmelfahrt is celebrated in the community of Augsburg (de_by_augsburg)
- Enhance tests

### CODE REVIEW

**Comment by spaceneedle2019** [comment]
@ppeble Yep, this PR should handle that issue. I used the map, too. Just the blue-colored Bavarian counties are celebrating "Mariä Himmelfahrt" in the shape of a public holiday (*de_by_cath*, cath for catholic).

```
   - name: Mariä Himmelfahrt
 -    regions: [de_by, de_sl]
 +    regions: [de_by_cath, de_by_augsburg, de_sl]
      mday: 15
```

**Comment by chinito** [comment]
LGTM, but we should implement de_by_prot or de_by_ev as well, as they have Buß und Betttag in some counties, don't they?

**Comment by spaceneedle2019** [comment]
@chinito:

Nope, _Buß- und Bettag_ is a public holiday in Saxony only. In Bavaria there is just a no-school arrangement.

https://de.wikipedia.org/wiki/Buß-_und_Bettag#Regelungen_in_Sachsen.2C_Bayern_und_Berlin

**Comment by chinito** [comment]
@spaceneedle2019 seems true. I thought there is something equivalent for the protestant heretics ROFL

I like your approach with :de_by_cath. 

Another question, how would we then deal with augsburg? It's part of :de_by_cath, too but has this additional holiday on 8th of august called Friedensfest.
This is a big issue in our internal calculation tool.

**Comment by spaceneedle2019** [comment]
@chinito Hmm, the current definition `de_by_augsburg` includes _Mariä Himmelfahrt_ and _Friedensfest_. Means, the only difference between `de_by_cath` and `de_by_augsburg` is the additional holiday Friedensfest.

What's the issue there? :)

```
  - name: Mariä Himmelfahrt
    regions: [de_by_cath, de_by_augsburg, de_sl]
    mday: 15
  - name: Friedensfest
    regions: [de_by_augsburg]
    mday: 8
```

**Comment by chinito** [comment]
Hmm, I would say the order is like so then: :de, :de_by, :de_by_cath, :de_by_cath_augsburg 
just from the perspective of logic.

right now it's just :de, :de_by, :de_by_augsburg

**Comment by spaceneedle2019** [comment]
@ppeble & @ttwo32

What's your opinion on this topic, guys? :)

(cc: @chinito)

**Comment by ppeble** [comment]
If I am understanding correctly I don't think this is possible right now. We don't have a kind of 'ordering' or way to make sure that `de_by_cath` comes before `de_cath_by_augsburg`. Would we be okay merging as-is and then opening an issue to address this? I am reworking things over in Rubyland and I think I would like to tackle some of the issues building up.

**Comment by spaceneedle2019** [comment]
@ppeble In my humble opinion it's a good compromise at the moment:
- *de_by_cath* describes different Catholic communities in Bavaria
- *de_by_augsburg* describes Augsburg, a (catholic) city in Bavaria with a bonus bank holiday

**Comment by ppeble** [comment]
@spaceneedle2019 Okay, I'm going to go ahead and merge before hearing back from @chinito. @chinito, I am totally happy to release a small update if you end up disagreeing with this. I promise I won't make you wait months again. 😦 

@chinito Would you mind opening up an issue so we can track this in this repo?

**Comment by spaceneedle2019** [comment]
Superb, @ppeble. So, if it's okay for @chinito, we can close issue #17, too. :)

**Comment by chinito** [comment]
@ppeble and @spaceneedle2019 feel free to merge. Maybach we leave it as it is and change augsburg if it gets more protestants than catholics. If we change I only wish for a deprecation warning beforehand. Otherwise things brake in our Augsburg Office 😂😂😂

**Comment by spaceneedle2019** [comment]
@chinito 🤣

**Pull request merged**
