### PR TITLE
Add July 15

### PR DESCRIPTION
**Pull request by saygun**
as [Wikipedia Link](https://en.wikipedia.org/wiki/Democracy_and_National_Unity_Day) shows July 15 is declared as national holiday

### CODE REVIEW

**Comment by spaceneedle2019** [comment]
@saygun 

Yep, since this year. Seems to be that not all known calendar sources adopted this new holiday yet. Is it a bank or a working holiday?

I think you should at the Wiki link to used sources in the header. :)

**Comment by saygun** [comment]
@spaceneedle2019 Wiki link added.

Yes It is bank holiday.

**Comment by ttwo32** [comment]
Good!!
Please use [year_range](https://github.com/holidays/definitions/blob/master/SYNTAX.md#year-ranges) from next time if you have a chance.
Thanks. 😄

**Comment by spaceneedle2019** [comment]
@ttwo32 (cc: @saygun) Yep, the `year_range` should be added to approve this enhancement.

```
  year_ranges:
    - after: 2017
```

**Comment by ppeble** [comment]
Hello again! This branch will now have conflicts since I just merged a rather big PR. I will handle fixing the issues and push up a new commit before merging. Thanks!

**Comment by saygun** [comment]
Hello folks. I just added `year_range` as you mentioned and updated tests.

**Comment by ppeble** [comment]
@saygun 😍 

This is perfect, thanks for changing the tests! I'll merge it right now and make sure it's included in the v6.0.0 release of the ruby gem, which should be happening soon. Just putting some final touches on some internal ruby pieces.

Thank you again!

**Pull request merged**
