### PR TITLE
UK - Add extra Bank Holiday for the Coronation of King Charles III

### PR DESCRIPTION
**Pull request by ryanharkins**

### CODE REVIEW

**Comment by hlascelles** [comment]
Proof / news: https://www.bbc.com/news/uk-63528830

**Comment by nick-vyrko** [comment]
https://www.gov.uk/bank-holidays

image

**Comment by hlascelles** [comment]
@ppeble Is this good to go for a new ruby gem please? It's coming up.

**Review by jlsync — APPROVED** [review]

**Comment by jlsync** [comment]
@ttwo32 @ppeble things are a bit quiet around here. Need some help?

**Comment by hlascelles** [comment]
@jlsync @Adam-Goddard1 @nikz @nick-vyrko @ppeble ... Looks like this ship is sailing. If you haven't monkey patched your code then your holiday detection will be wrong on Monday.

**Review by jlsync — APPROVED** [review]

**Pull request merged**
