### PR TITLE
Remove methods from Korean definitions, use lunar_to_solar instead

### PR DESCRIPTION
**Pull request by jonathanpike**
This PR updates the definitions for the Republic of Korea to use the `lunar_to_solar` method introduced in my [PR](https://github.com/holidays/holidays/pull/261) on the Holidays gem.

### CODE REVIEW

**Comment by ptrimble** [comment]
Thank you for this! I'll review it this week and get back to you. 👍

**Comment by ptrimble** [comment]
Oh, also wanted to drop this in: I recognize the current pain of adding a method to the ruby repository just so it can be used in these definitions. The defining of these kinds of 'common' methods is something that is on my mind.

Quick example of how I envision things going in the (probably not near) future:

1) Imagine we have a 'ruby' version of holidays, a 'Go' version of holidays', and a 'swift' version of holidays
2) You, JP (can I call you JP? 😛), submit this definition change, which assumes a 'lunar_to_solar' method is available so when code is generated in the respective languages it will not fail
3) You add the method to ruby but not to the Go or Swift versions.

How do we handle this? Now if someone pulls in the latest definitions in Go or Swift things will fail until the logic is implemented.

Currently I am leaning towards defining some kind of list of 'accepted' or 'commonly available' methods that any repository using these definitions must implement. If a specific repository decides to use the latest definitions then yeah, things will fail until it updates to include the new definition. This feels reasonable to me.

Anyway, you don't need to comment on this necessarily, just throwing out my thoughts, which helps me pick out problems with it before I start any kind of implementation. Thanks for being flexible in this time where there doesn't seem to be any benefit to having these definitions remain separate. 👍

**Comment by jonathanpike** [comment]
Hey Phil, 

Thanks for the explanation.  I had a couple of thoughts regarding implementing the main library in other languages and sharing definitions. 

In the case that there were Holidays libraries in other languages, I think that it would likely be trivial to re-implement methods (such as the Lunar Holidays methods I committed), given that there is already an implementation that works.  It's just a matter of adapting the Ruby code (in this example) to something like Go or Swift.  I don't think that it's necessarily a good thing for the library to break for a PR like this one. 

With that said, who would do the re-implementation?  That, I think, is the real issue.  The person issuing the PR may not have experience with the languages that the other libraries are written in, and so would do a sub-par job (likely).  And if there are a lot of other libraries in the future, this could be onerous.  Maybe there could be a maintainer who has experience in all the languages that are supported and could do this job, but that's just more work for the maintainers.  

One other solution would be to identify all of the other global methods that could potentially be needed, and make a canonical implementation of them for the library (this could be in the issues for contributors to implement, even... maybe a good thing for a first time contributor to do, given that the problem of actually implementing the code for the first time is complete).  

These are just some thoughts, not sure if you have to do anything with them.  I'm super stoked about the future of Holidays, though, and think it's a great project! Thanks for all the work you do.

**Comment by ppeble** [comment]
Aw, poop, I didn't realize that these would conflict. I'll fix it real quick and then I'll merge this and the matching one on the ruby repo.

**Comment by ppeble** [comment]
@jonathanpike Oh, and thank you for your feedback! I did think of the contributor problem but...I guess I figured that either I or any other maintainers that were responsible for the repos would need to do it. I recognize the downsides (i.e. the work it would take to keep it all up to date) but...I'm not confident that we could come up with a DSL to represent the sometimes wonky logic in these different 'common' holidays. I mean, Easter is nuts, and so are some of the other ones.

That said, I am at least going to TRY to do it that way so that each language can generate its own version of the canonical methods. But I'm just not confident. So, I guess in short: I will try the 'implement the methods in YAML' option first before requiring each language to implement it itself. But we will see! For starters I have the 'test' portion of the code nearly done in Ruby (to generate tests from YAML instead of just copy/pasted the ruby into the tests) so at least that part will be done. 😄

**Comment by ppeble** [comment]
Oh wow, I haven't used the Github 'resolve conflicts' tool yet. It's great! 😍 

We don't have it yet in our enterprise version of Github at my day job. I love it!

**Pull request merged**
