### PR TITLE
Update Korean holiday

### PR DESCRIPTION
**Pull request by marocchino**
- Korean New Year is 3 days
- Use Korean language

BTW, How can I run test in `kr.yaml` file?
I tried `bundle exec rspec`, `make validate`.
But, It seems not works.

### CODE REVIEW

**Comment by ttwo32** [comment]
Hi @marocchino !!
Thank yot for adding new holidays.😄
Would you like  try `make test` ?

**Comment by ppeble** [comment]
Hi @marocchino! I'll add my thanks to @ttwo32's. 

Unfortunately I've let a few PRs get backed up in the queue so I'll need to merge https://github.com/holidays/definitions/pull/32 first. I'll do that this weekend.

As for testing, running `make validate` is good enough for this repo. We have split out the YAML definitions into their own repository. The ruby repository will take these and generate the final definitions that are used in the gem. That is the place that they will be fully tested.

You've caught us in a transition period, so things are not totally smooth yet. I plan on setting up auto-testing in the future so you won't have to worry about it. 😄 

I'll get back to you shortly about merging down these changes. Thanks again!

**Comment by marocchino** [comment]
@ppeble I rebased this. Can you review it again, please?

**Comment by ppeble** [comment]
Thank you @marocchino for the submission and thank you for your patience! ❤️

**Pull request merged**
