### PR TITLE
Fixed Canadian province/territory codes

### PR DESCRIPTION
**Pull request by slucaskim**
from https://en.wikipedia.org/wiki/Provinces_and_territories_of_Canada
image
image

### CODE REVIEW

**Comment by slucaskim** [comment]
If approved, please also update the holidays gem so that I could use these fixes! Thank you

**Comment by ptrimble** [comment]
Good change! I'll merge and test it out and get it out as 5.3.0. Thank you!

**Comment by ptrimble** [comment]
This is released as v5.3.0. Thanks again!

**Comment by ttwo32** [comment]
@slucaskim Sorry for slow response.This is good !!Thank you!! 😄 
@ptrimble Thank you for merging this PR and release. :)

**Pull request merged**
